name: motorsport
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  get: ^4.7.2
  google_fonts: ^6.3.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Urbanist
  #     fonts:
  #       - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
  #         weight: 100
  #       - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
  #         weight: 200
  #       - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
  #         weight: 900
flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ''
